services:
  fiap.mctech.payment.api:
    depends_on:
      - sqlserver
      - keycloak
    image: ${DOCKER_REGISTRY-}mctech/payment-api
    build:
      context: .
      dockerfile: dockerfiles/Payment.Dockerfile

  fiap.mctech.order.api:
    depends_on:
      - sqlserver
      - keycloak
    image: ${DOCKER_REGISTRY-}mctech/order-api
    build:
      context: .
      dockerfile: dockerfiles/Order.Dockerfile

  fiap.mctech.cart.api:
    depends_on:
      - redis
      - keycloak
    image: ${DOCKER_REGISTRY-}mctech/cart-api
    build:
      context: .
      dockerfile: dockerfiles/Cart.Dockerfile
  
  redis:
    image: redis:latest
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    restart: always
    command: start-dev
    environment:
      KC_HOSTNAME: keycloak