services:
  fiap.mctech.payment.api:
    container_name: mctech_payment_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      CONNECTION_STRING: Server=sqlserver,1433;Initial Catalog=mctech_payments;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;
      ALLOW_SWAGGER_UI: true

      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
      OPENID_AUDIENCE: ${OPENID_AUDIENCE}
    ports:
      - "9001:8081"
    networks:
      - local_network
      - db_network

  fiap.mctech.order.api:
    container_name: mctech_order_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8081
      CONNECTION_STRING: Server=sqlserver,1433;Initial Catalog=mctech_order;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;
      ALLOW_SWAGGER_UI: true

      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
      OPENID_AUDIENCE: ${OPENID_AUDIENCE}

      MCTECH_CART_SERVICE: ${MCTECH_CART_SERVICE}
      MCTECH_PAYMENT_SERVICE: ${MCTECH_PAYMENT_SERVICE}

    ports:
      - "9002:8081"
    networks:
      - local_network 
      - db_network

  fiap.mctech.cart.api:
    container_name: mctech_cart_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      OPENID_AUTHORITY: ${OPENID_AUTHORITY}
      OPENID_AUDIENCE: ${OPENID_AUDIENCE}
      REDIS_CONNECTION: redis:6379
    ports:
      - "9003:80"
      #- "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - local_network
      - db_network

  redis:
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - db_network

  sqlserver:
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - db_network

  keycloak:
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
  db_network:

volumes:
  sqlserver_data:
  keycloak_data: