services:
  fiap.mctech.payments.api:
    depends_on:
      - sqlserver
      - keycloak
    image: ${DOCKER_REGISTRY-}mctech/api-payments
    build:
      context: .
      dockerfile: ../src/Fiap.McTech.Payments.Presentation.API/Dockerfile

  fiap.mctech.api.order:
    depends_on:
      - sqlserver
      - keycloak
    image: ${DOCKER_REGISTRY-}mctech/orders-api
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile

  fiap.mctech.cart.api:
    depends_on:
      - redis
      - keycloak
    image: ${DOCKER_REGISTRY-}fiapmctechcartapi
    build:
      context: .
      dockerfile: src/Fiap.McTech.Cart.Api/Dockerfile
  
  redis:
    image: redis:latest
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    restart: always
    command: start-dev
    environment:
      KC_HOSTNAME: keycloak